version: '3'
services:
  #
  app:
    image: node:14-alpine3.13
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    command: tail -f /dev/null
    volumes:
      - ./:/var/www
    links:
      # - redis
      - mongodb
    networks:
      - app-network

  # Mongo Service
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    tty: true
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: Lofm
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
