version: '3'
services:
  #PHP Service
  app:
    image: node:10-alpine
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    command: tail -f /dev/null
    volumes:
      - ./:/var/www
    links:
      - redis
    networks:
      - app-network

  mysqldb:
    image: mysql:5.7.22
    container_name: mysqldb
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: softwareCheckout
      MYSQL_ROOT_PASSWORD: softwareCheckout123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  #MySQL Service
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    tty: true
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: Lofm
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    tty: true
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
