module.exports = [
  {
    email: 'bomholmm@miamioh.edu',
    status: 'active',
    groups: [
      '_deployment_admin',
      '_support_admin',
      'ActiveAffiliation',
      'library patron illustrator',
      'library patron photoshop',
      'Library API test',
      '_admin_Library API test',
    ],
    username: 'bomholmm@miamioh.edu',
    adminRoles: ['org', 'deployment', 'support'],
    domain: 'miamioh.edu',
    firstname: 'Michael',
    lastname: 'Bomholt',
    country: 'US',
    type: 'federatedID',
  },
  {
    email: 'irwinkr@miamioh.edu',
    status: 'active',
    groups: [
      '_support_admin',
      'ActiveAffiliation',
      'library patron illustrator',
      'library patron photoshop',
      '_admin_Library Patron Full CC',
      '_admin_Library Staff Full CC libcal',
      'Library API test',
      '_admin_Library API test',
    ],
    username: 'irwinkr@miamioh.edu',
    adminRoles: ['org', 'support'],
    domain: 'miamioh.edu',
    firstname: 'Ken',
    lastname: 'Irwin',
    country: 'US',
    type: 'federatedID',
  },
];
